In [17]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])  #1d array
print(a)

[1 2 3 4]


In [3]:
print(a[:2])

[1 2]


In [4]:
import time  #list time
lst = [1] * 10**6
start = time.time()
lst = [x + 2 for x in lst]
print("List operation time:", time.time() - start)

List operation time: 0.05099987983703613


In [6]:
arr = np.ones(10**6)   #numpy time
start = time.time()
arr = arr + 2
print("NumPy operation time:", time.time() - start)

NumPy operation time: 0.0019998550415039062


In [7]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])  #2d array
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [8]:
print(b[1,0])

4


In [9]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])   #3d array
print(arr)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [10]:
#creating array from list
lis=[1,2,3,4,5]
array_Lis=np.array(lis)
array_Lis

#if list has diff types
lis1=[1,2.5,3,4,5.6]
array_lis=np.array(lis1)
array_lis

array([1. , 2.5, 3. , 4. , 5.6])

In [11]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

3
(2, 3, 4)
24
int32


In [12]:
print(array_lis.dtype)
print(array_lis.shape)
print(b.shape)

float64
(5,)
(3, 3)


In [13]:
#ones and zeros
print(np.zeros(5,dtype='int32'))    #data-type change
print(np.ones(5))
print(np.arange(10,60,10))          #arange function
print(np.linspace(0,10,5))          #linspace function
print(np.empty(3,dtype='S'))        #empty function

[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[10 20 30 40 50]
[ 0.   2.5  5.   7.5 10. ]
[b'\xb8' b'7' b'P']


In [72]:
print(b)
reshaped_array=np.reshape(b,(1,9),order='C')     #reshape
print("Reshaped array: ",reshaped_array)

print("Transpose of matrix: ",b.transpose())                #transpose

raveled_array=np.ravel(b)    #ravel
print("Ravelled array: ",raveled_array)

b.flatten()                  #flatten

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array:  [[1 2 3 4 5 6 7 8 9]]
Transpose of matrix:  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Ravelled array:  [1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#array operations
a1=np.array([1,2,3,4,5,6])
print("Sum of elements in 1d array: ",a1.sum()) 
print("Max element in 1d array: ",a1.max())
print("Min element in 1d array: ",a1.min())

b1=np.array([[1,2],[3,4]])
b2=np.array([[2,1],[4,3]])
print("2D array:")
print(b1)

print("column addition: ",b1.sum(axis=0))
print("row addition: ",b1.sum(axis=1))

Sum of elements in 1d array:  21
Max element in 1d array:  6
Min element in 1d array:  1
2D array:
[[1 2]
 [3 4]]
column addition:  [4 6]
row addition:  [3 7]


In [36]:
print("Broadcasting: ",a1*2)
print(b1+b2)
# print(a1+b1) this will get value error because a1 is 1D and b1 is 2D

Broadcasting:  [ 2  4  6  8 10 12]
[[3 3]
 [7 7]]


In [57]:
random_no=np.random.rand(3)          #1D matrix
print(random_no)
random_nos=np.random.rand(2,2)       #2D matrix
print(random_nos)

[0.2875374  0.33009038 0.75077505]
[[0.94770293 0.60780973]
 [0.94621541 0.38802795]]


In [59]:
rns=np.random.randint(1,10,size=(3,3))   #within range
print(rns)
rnn=np.random.normal(5,2,size=(3,3))   #normal distribution
print(rnn)
sample = np.random.choice([1, 2, 3, 4, 5], size=3)  # Random sample of 3 elements from the list
print(sample)

[[7 8 8]
 [4 6 9]
 [7 7 8]]
[[8.01787261 4.78971775 2.88902532]
 [3.58578085 3.57163888 5.8197136 ]
 [5.50045966 4.9290087  5.72452807]]
[5 4 3]


In [75]:
a2=[1,1,2,3,3,3,4,5]
print("Unique elements in array: ",np.unique(a2))                                       #unique
unique_values, indices_list,count= np.unique(a2, return_index=True,return_counts=True)
print(unique_values,indices_list,count)

print("Reverse array: ",np.flip(a2))                                                   #reverse array

Unique elements in array:  [1 2 3 4 5]
[1 2 3 4 5] [0 2 3 6 7] [2 1 3 1 1]
Reverse array:  [5 4 3 3 3 2 1 1]


In [ ]:
np.save('samplepy.py',a2)
np.savetxt('sampletxt.csv',a2)

In [ ]:
y= np.array([1, 2, 3,4,5,6])
result = np.split(y,3) 
print(result)